name: ToDo
description: A new flutter project.
dependencies:
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/logo_light.png
    - assets/logo_dark.png
    - assets/logo_clear.png
    - assets/text.png